SELECT * FROM customer_churn_db.customerchurn;
SHOW DATABASES;
USE customer_churn_db;
SHOW TABLES;
-- Q1. Display all customer details

SELECT *
FROM customerchurn;

-- Q2. Find all customers who are on the Premium subscription plan
SELECT *
FROM customerchurn
WHERE subscription_plan = 'Premium';

-- Q3.Count the total number of customers
SELECT COUNT(*) AS total_customers
FROM customerchurn;

-- Q4. List all customers from India
SELECT customer_id,
       customer_name,
       country
FROM customerchurn
WHERE country='India';

-- Q5.Find customers whose monthly fee is greater than 20
SELECT customer_name,
       monthly_fee
FROM customerchurn
WHERE monthly_fee > 20;

-- Q6. Count how many customers have churned
SELECT COUNT(*) AS churned_customers
FROM customerchurn
WHERE churn_status='Yes';

-- Q7. Show customer name, subscription plan, and total revenue sorted by highest revenue
SELECT customer_name,
       subscription_plan,
       total_revenue
FROM customerchurn
ORDER BY total_revenue DESC;

-- Q8 . Calculate the average monthly fee for each subscription plan
SELECT subscription_plan,
       ROUND(AVG(monthly_fee),2) AS average_fee
FROM customerchurn
GROUP BY subscription_plan;

-- Q9. Find the Top 10 customers with highest revenue
SELECT customer_name,
       total_revenue
FROM customerchurn
ORDER BY total_revenue DESC
LIMIT 10;

-- Q10. Count customers by country and subscription plan
SELECT country,
       subscription_plan,
       COUNT(*) AS total_customers
FROM customerchurn
GROUP BY country,subscription_plan
ORDER BY country;

-- Q11 .Average login frequency of churned customers
SELECT ROUND(AVG(login_frequency),2) AS avg_login
FROM customerchurn
WHERE churn_status='Yes';

-- Q12. Total revenue generated by each subscription plan
SELECT subscription_plan,
       SUM(total_revenue) AS revenue
FROM customerchurn
GROUP BY subscription_plan;

-- Q.13 Calculate Overall Churn Rate
SELECT
ROUND(
COUNT(CASE WHEN churn_status='Yes' THEN 1 END)
*100.0/COUNT(*),2
) AS churn_rate
FROM customerchurn;

-- Q.14 Find the month having highest customer signups
SELECT DATE_FORMAT(signup_date,'%Y-%m') AS signup_month,
       COUNT(*) AS total_signups
FROM customerchurn
GROUP BY signup_month
ORDER BY total_signups DESC
LIMIT 1;
-- Q15. Rank customers by revenue within each subscription plan
SELECT customer_name,
       subscription_plan,
       total_revenue,
       RANK() OVER(
       PARTITION BY subscription_plan
       ORDER BY total_revenue DESC
       ) AS revenue_rank
FROM customerchurn;

-- Q16 Cohort Analysis
SELECT DATE_FORMAT(signup_date,'%Y-%m') AS cohort_month,
       COUNT(*) AS total_customers
FROM customerchurn
GROUP BY cohort_month
ORDER BY cohort_month;

-- Q17. Most common churn reason
SELECT churn_reason,
       COUNT(*) AS total_customers
FROM customerchurn
WHERE churn_status='Yes'
GROUP BY churn_reason
ORDER BY total_customers DESC
LIMIT 1;

